jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reposirory
        user: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18x
          cache: 'npm'

      - name: Install depedencies
        run: npm install

      - name: Build
        run: npm run build
